"""Download proper AI training datasets from HuggingFace.

This replaces the skill-markdown training with real datasets that
produce models capable of coherent, intelligent responses.

Datasets used:
1. TinyStories (pre-training) — proven to work at 1M-33M param scale
2. Alpaca-GPT4 (SFT) — 52K high-quality instruction pairs from GPT-4
3. Dolly-15K (SFT) — human-written instruction pairs, commercially licensed

Usage:
    pip install datasets
    python scripts/download_training_data.py
"""

import os
import sys
import json
from pathlib import Path

# Check for datasets library
try:
    from datasets import load_dataset
except ImportError:
    print("Installing datasets library...")
    os.system(f"{sys.executable} -m pip install datasets --trusted-host pypi.org --trusted-host files.pythonhosted.org -q")
    from datasets import load_dataset

DATA_DIR = Path(__file__).parent.parent / "trio_model" / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)


def download_tinystories():
    """Download TinyStories — pre-training corpus proven at 1M-33M param scale.

    Microsoft Research showed models as small as 1M params generate coherent
    English when trained on this data.
    """
    print("\n[1/3] Downloading TinyStories (pre-training corpus)...")
    print("  Source: roneneldan/TinyStories (Microsoft Research)")

    output = DATA_DIR / "pretrain_tinystories.txt"
    if output.exists() and output.stat().st_size > 100_000_000:
        print(f"  Already exists ({output.stat().st_size / 1e6:.0f}MB). Skipping.")
        return

    ds = load_dataset("roneneldan/TinyStories", split="train")

    # Take a subset — full dataset is 2.1M stories, we use 500K for nano
    subset_size = 500_000
    print(f"  Using {subset_size:,} stories out of {len(ds):,}")

    with open(output, "w", encoding="utf-8") as f:
        for i, row in enumerate(ds):
            if i >= subset_size:
                break
            text = row.get("text", "")
            if text.strip():
                f.write(text.strip() + "\n\n")
            if (i + 1) % 100_000 == 0:
                print(f"  Processed {i+1:,} stories...")

    size_mb = output.stat().st_size / 1e6
    print(f"  Saved: {output} ({size_mb:.0f}MB)")


def download_alpaca_gpt4():
    """Download Alpaca-GPT4 — 52K instruction pairs generated by GPT-4.

    Same prompts as Stanford Alpaca but with GPT-4 quality responses.
    Best quality-to-size ratio for instruction tuning.
    """
    print("\n[2/3] Downloading Alpaca-GPT4 (instruction tuning)...")
    print("  Source: vicgalle/alpaca-gpt4")

    output = DATA_DIR / "sft_alpaca_gpt4.jsonl"
    if output.exists() and output.stat().st_size > 10_000_000:
        print(f"  Already exists ({output.stat().st_size / 1e6:.0f}MB). Skipping.")
        return

    ds = load_dataset("vicgalle/alpaca-gpt4", split="train")
    print(f"  Downloaded {len(ds):,} instruction pairs")

    count = 0
    with open(output, "w", encoding="utf-8") as f:
        for row in ds:
            instruction = row.get("instruction", "").strip()
            inp = row.get("input", "").strip()
            output_text = row.get("output", "").strip()

            if not instruction or not output_text:
                continue

            # Build prompt
            if inp:
                prompt = f"{instruction}\n\nInput: {inp}"
            else:
                prompt = instruction

            f.write(json.dumps({
                "instruction": prompt,
                "response": output_text,
            }, ensure_ascii=False) + "\n")
            count += 1

    size_mb = Path(DATA_DIR / "sft_alpaca_gpt4.jsonl").stat().st_size / 1e6
    print(f"  Saved: {count:,} pairs ({size_mb:.0f}MB)")


def download_dolly():
    """Download Databricks Dolly-15K — human-written, commercially licensed.

    100% human-written by Databricks employees. Covers 8 categories:
    brainstorming, classification, QA, generation, extraction, summarization.
    """
    print("\n[3/3] Downloading Dolly-15K (human-written instructions)...")
    print("  Source: databricks/databricks-dolly-15k")

    output = DATA_DIR / "sft_dolly.jsonl"
    if output.exists() and output.stat().st_size > 1_000_000:
        print(f"  Already exists ({output.stat().st_size / 1e6:.0f}MB). Skipping.")
        return

    ds = load_dataset("databricks/databricks-dolly-15k", split="train")
    print(f"  Downloaded {len(ds):,} instruction pairs")

    count = 0
    with open(output, "w", encoding="utf-8") as f:
        for row in ds:
            instruction = row.get("instruction", "").strip()
            context = row.get("context", "").strip()
            response = row.get("response", "").strip()

            if not instruction or not response:
                continue

            # Build prompt
            if context:
                prompt = f"{instruction}\n\nContext: {context}"
            else:
                prompt = instruction

            f.write(json.dumps({
                "instruction": prompt,
                "response": response,
            }, ensure_ascii=False) + "\n")
            count += 1

    size_mb = Path(DATA_DIR / "sft_dolly.jsonl").stat().st_size / 1e6
    print(f"  Saved: {count:,} pairs ({size_mb:.0f}MB)")


def merge_sft_data():
    """Merge all SFT datasets + trio skills into one file."""
    print("\n[Merging] Combining all SFT data...")

    merged = DATA_DIR / "sft_merged.jsonl"
    total = 0

    with open(merged, "w", encoding="utf-8") as out:
        # Alpaca-GPT4
        alpaca = DATA_DIR / "sft_alpaca_gpt4.jsonl"
        if alpaca.exists():
            for line in open(alpaca, encoding="utf-8"):
                out.write(line)
                total += 1

        # Dolly
        dolly = DATA_DIR / "sft_dolly.jsonl"
        if dolly.exists():
            for line in open(dolly, encoding="utf-8"):
                out.write(line)
                total += 1

        # Original trio skills SFT (keep our domain knowledge)
        skills_sft = DATA_DIR / "sft_data.jsonl"
        if skills_sft.exists():
            for line in open(skills_sft, encoding="utf-8"):
                out.write(line)
                total += 1

    size_mb = merged.stat().st_size / 1e6
    print(f"  Total SFT pairs: {total:,} ({size_mb:.0f}MB)")
    print(f"  Saved: {merged}")


def merge_pretrain_data():
    """Merge TinyStories + trio skills into one pretrain file."""
    print("\n[Merging] Combining all pre-training data...")

    merged = DATA_DIR / "pretrain_merged.txt"

    with open(merged, "w", encoding="utf-8") as out:
        # TinyStories first (teaches language)
        ts = DATA_DIR / "pretrain_tinystories.txt"
        if ts.exists():
            for line in open(ts, encoding="utf-8"):
                out.write(line)

        # Then trio skills (teaches domain knowledge)
        skills = DATA_DIR / "train.txt"
        if skills.exists():
            out.write("\n\n")
            for line in open(skills, encoding="utf-8"):
                out.write(line)

    size_mb = merged.stat().st_size / 1e6
    print(f"  Total pretrain data: {size_mb:.0f}MB")
    print(f"  Saved: {merged}")


if __name__ == "__main__":
    print("=" * 60)
    print("  TRIO.AI — Downloading Training Data from HuggingFace")
    print("=" * 60)

    download_tinystories()
    download_alpaca_gpt4()
    download_dolly()
    merge_sft_data()
    merge_pretrain_data()

    print("\n" + "=" * 60)
    print("  Download complete!")
    print()
    print("  Pre-training: pretrain_merged.txt (TinyStories + skills)")
    print("  SFT: sft_merged.jsonl (Alpaca-GPT4 + Dolly + skills)")
    print()
    print("  Next: python scripts/train_default_model.py --reset")
    print("=" * 60)
